apiVersion: 1

datasources:
  - name: PostgreSQL-Competitive
    type: postgres
    access: proxy
    url: postgres:5432
    user: jackdaw
    isDefault: false
    jsonData:
      database: jackdaw
      sslmode: require
    secureJsonData:
      password: $POSTGRES_PASSWORD

  - name: Competitive-Metrics
    type: grafana-simple-json-datasource
    access: proxy
    url: https://competitive-dashboard:8080
    isDefault: true
